Ciwemb 289 total
compucorp/io.compuco.financeextras pull request #29
Opened 2023-05-24 09:16 UTC by olayiwola-compucorp

## Overview

## Before

## After

## Technical Details
_

2023-05-24 14:32 UTC, omarabuhussein requested changes
left some notes,

also again the idea is that you are using the API to calculate the tax is irrelevant from user perceptive, so it only should be mention in the technical description or the commit message body (not the commit message short title).

So I would change this PR title to:

```
CIWEMB-289: Show real time amounts updates when updating line items on credit note creating form.
``

the "before" and "after" sections should be updated with that in mind as well.

2023-05-24 14:32 UTC, omarabuhussein commented on CRM/Financeextras/BAO/CreditNote.php
> +  public static function getSubTotal(array $item) {
getSubTotal -> getLineItemSubTotal


also it should be `private` given it is not used anywhere outside the class

2023-05-24 15:42 UTC, olayiwola-compucorp commented on CRM/Financeextras/BAO/CreditNote.php
> +    usort($items, fn ($a, $b) => $a['tax_rate'] <=> $b['tax_rate']);
not explicitly stated, but we did it for Quotations and thought it would be nice to have here also.

2023-05-25 08:15 UTC, omarabuhussein approved these changes

2023-05-25 08:15 UTC, merged